---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test on Lint
    runs-on: unbuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secret.DOCKERHUB_USER}}
          password: ${{ secret.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          username: ${{ secret.DOCKERHUB_USER}}
          password: ${{ secret.DOCKERHUB_TOKEN}}
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Link
        run: docker-compose run --rm app sh -c "flake8"